### ISSUE TITLE
Difficulties importing interchange

### ISSUE THREAD

**Issue by annamherz** [openforcefield/openff-interchange#498] opened 2022-08-09 08:33 UTC
Hello! I've been trying to follow the example here on the github in the README:

```
from openff.toolkit import Molecule, ForceField
from openff.units import unit
from openff.interchange import Interchange

# Use the OpenFF Toolkit to generate a chemical topology
molecule = Molecule.from_smiles("CCO")
molecule.generate_conformers(n_conformers=1)
topology = molecule.to_topology()
topology.box_vectors = unit.Quantity([4, 4, 4], unit.nanometer)

# Load OpenFF 2.0.0 "Sage"
sage = ForceField("openff-2.0.0.offxml")

# Create an Interchange object
out = Interchange.from_smirnoff(force_field=sage, topology=topology)

# Convert the Interchnage object to an OpenMM System
omm_sys = out.to_openmm(combine_nonbonded_forces=True)

# or write to GROMACS files
out.to_gro("out.gro")
out.to_top("out.top")

# or roundtrip through JSON or other common serialization formats
roundtripped = Interchange.parse_raw(out.json())
```
however, I am having problems importing. `openff.toolkit import ForceField` is not possible to import, and neither is from `openff.interchange import Interchange` which throws the following exception:
`cannot import name 'Interchange' from 'openff.interchange' (/home/anna/anaconda3/envs/biosimspace-dev/lib/python3.9/site-packages/openff/interchange/__init__.py)`

I have installed interchange using the conda channel and the version is 0.1.4 .

Thank you!

**Comment by mattwthompson** [comment] 2022-08-09 08:50
Hi,

Normally there isn't a huge difference between the development heads of our projects and the released versions, but at the moment there are some pretty big ones. The shorter import paths from both `openff.toolkit` and `openff.interchange` (along with tons of other changes) are in the `main` branches but not yet in releases (0.11.0 and 0.2.0, respectively), though we hope the releases come within the next week or two. There _are_ conda packages up, but they're on off-main labels. We don't anticipate major changes prior to release, so if you want to try them out, this should update your conda environment (I think we're on 0.11.0rc3 and 0.2.0rc3):

```
$ conda update "openff-interchange >=0.2.0rc3" "openff-toolkit >=0.11.0rc3" -c conda-forge/label/openff-interchange_rc -c conda-forge/label/openff-toolkit_rc -c conda-forge
```

That might be slow if you're using `conda`, so `mamba` as a drop-in replacement is recommended. Your other option is to directly install from the repos, I think the syntax is like

```
$ pip install git+https://github.com/openforcefield/openff-toolkit.git@main
$ pip install git+https://github.com/openforcefield/openff-interchange.git@main
$ conda install cachetools cached-property  # new dependencies, conda will bring them in put pip git+ won't
```

If that doesn't work, the safest option is to create a new conda environment; this one-liner should bring in everything you need:

```
$ conda create -n offtk-011rc -c conda-forge/label/openff-interchange_rc -c conda-forge/label/openff-toolkit_rc -c conda-forge "openff-toolkit-examples >=0.11.0rc2"
```

Once the RCs become proper releases, this will all simplify down again to i.e.

```
$ conda install openff-toolkit -c conda-forge
```

but for the current release cycle it's a bit rocky - my apologies.


cc: @j-wags is the Confluence link in your 7/7/22 post in #general the best reference to use for this?

**Comment by annamherz** [comment] 2022-08-09 09:47
Great, thank you so much!

**Comment by mattwthompson** [comment] 2022-08-19 21:09
It seems like the issue is resolved, so I'm going to close this. Feel free to re-open this or new issues if you face difficulties in the future.

Soon there will be a full 0.2.0 release which will bring about a year of updates into the simple `conda install openff-interchange -c conda-forge` install.

**Closed by mattwthompson** 2022-08-19 21:09 UTC
