### ISSUE TITLE
describing pi orbitals for rings

### ISSUE THREAD

**Issue by peterjohncherry** [openforcefield/openff-interchange#730] opened 2023-05-24 13:34 UTC
[benzene_trouble.tar.gz](https://github.com/openforcefield/openff-toolkit/files/11555131/benzene_trouble.tar.gz)
**Describe the bug**

I'm currently trying to run simulations using the Smirnoff Forcefield in combination the virtual sites generated by the [Astex ESP  DNN](https://github.com/AstexUK/ESP_DNN/tree/master/esp_dnn) but am running into some problems.

I want to add virtual sites above and below the ring to describe the pi electrons  (please see benzene_astex.pdb.pqr). These virtual sites should be along the vector perpendicular to the plane of the ring. To do this I was planning to use the TrivalentLonePair class. However, when I try to do this the position of the virtual sites appears to be along some different vector entirely (see attached). Am I defining the sites incorrectly somehow? I can see there might be an issue when all the atoms lie in a plane. Adding a virtual site using the TrivalentLonePair works fine for me when defining a site on ammonia. 

Furthermore, even though I've got two different types of sites (one above and one below the plane), and have defined each of these with different names (EP+ and EP-), I'm only seeing sites in one position. Confusingly, it is adding two virtual sites for each carbon, one for each name, they just are added in the same positions (please see trajectory.pdb)

**To Reproduce**
Please run 
python vsite_example.py benzene.sdf benzene_vsites.offxml

Sorry, vsite_example.py is a bit long, but it's basically just taken directly from the [example notebook](https://github.com/openforcefield/openff-toolkit/blob/main/examples/virtual_sites/vsite_showcase.ipynb) provided on the openff-toolkit github; I figured this was the best way to minimize the chance of me introducing any errors.

I'm running using openff-toolkit 0.11.4 , I wouldn't have thought this should be an issue as I have not seen anything relevant in the bugfix reports in more recent releases. 

**Output**
The output is trajectory.pdb. 

**Computing environment (please complete the following information):**

 - Operating system : ubuntu 24.04 LTS
 - Output of running `conda list` : I'm actually not using a conda environment, but the output of pip list is attached and in pyflare_env. The reason for this is that the company I work for (Cresset) has it's own python build (pyflare), but I've attached the output of pyflare -m pip list, which should be roughly equivalent.
 

**Additional context**
I can work round this issue by using MonovalentLonePair and assigning the parent atom to be the hydrogen, but this isn't a viable solution for all systems to which I want to add this kind of virtual site. 

Many Thanks,

Peter

**Comment by peterjohncherry** [comment] 2023-05-26 18:04
Hi. Thanks very much for this detailed response. I think I understand it, but was actually on study leave today and won't be back work until Tuesday, so will go back over it then and might get back to you.

Sorry about the questions in the script comments, I'd forgot I'd left them in there; they're sort of me talking to myself....

**Comment by mark-cresset** [comment] 2024-03-05 09:42
Just a ping on this one - we're at a fairly advanced stage of building a force field based on openFF + lots of virtual sites, and the inability to specify an out-of-plane virtual site on an sp2 atom is becoming difficult - we currently have to set up the system with the OpenFF tools and then fiddle with the OpenMM state directly, which is less than optimal. Are there any plans currently to extend the VS code to handle this type of system?

**Comment by mattwthompson** [comment] 2024-03-05 15:33
One of the underlying issues (https://github.com/openforcefield/openff-toolkit/issues/1363) is unresolved and @j-wags would be the point person on it

I can work around it by defining different SMIRKS patterns to re-orient the reference frames; the physics here are surely garbage but the OpenMM object defines multiple virtual sites in reference frames such that they should be pointing in opposite directions with respect to a C-C-C-H quartet that defines them.

```python
import openmm
import openmm.app
import openmm.unit
from openff.toolkit import ForceField, Molecule, Quantity, Topology

benzene = Molecule.from_smiles("c1ccccc1")
benzene.generate_conformers(n_conformers=1)

if False:
    topology = Topology.from_molecules(
        [
            benzene,
            benzene,
        ]
    )

    topology.box_vectors = Quantity([4, 4, 4], "nanometer")

    positions = topology.get_positions()
    positions[int(positions.shape[0] / 2) :, :] += Quantity([0, 0, 0.3], "nanometer")
    topology.set_positions(positions)
else:
    topology = benzene.to_topology()

forcefield = ForceField("openff-2.1.0.offxml")
virtual_site_parameters = forcefield.get_parameter_handler("VirtualSites")

for smirks, name in zip(
    [
        "[#6:1](~[#6:2])(~[#6:3])(~[#1:4])",
        "[#6:1](~[#6:3])(~[#6:2])(~[#1:4])",
    ],
    [
        "EP+",
        "EP-",
    ],
):
    virtual_site_parameters.add_parameter(
        parameter_kwargs={
            "smirks": smirks,
            "epsilon": Quantity(0.0, "kilocalories_per_mole"),
            "type": "TrivalentLonePair",
            "match": "once",
            "distance": Quantity(0.4, "angstrom"),
            "outOfPlaneAngle": None,
            "inPlaneAngle": None,
            "charge_increment1": Quantity(0.1, "elementary_charge"),
            "sigma": Quantity(0.0, "angstrom"),
            "name": name,
        },
    )

interchange = forcefield.create_interchange(topology=topology)

interchange.minimize()

# something's wrong with the initial positions, but
interchange.to_pdb("initial.pdb", include_virtual_sites=True)

# the virtual site parameters here look good
with open("system.xml", "w") as f:
    f.write(
        openmm.XmlSerializer.serialize(
            interchange.to_openmm(
                combine_nonbonded_forces=True,
            ),
        ),
    )

simulation = interchange.to_openmm_simulation(
    integrator=openmm.LangevinIntegrator(
        300,
        1,
        0.001,
    )
)

dcd_reporter = openmm.app.DCDReporter("trajectory.dcd", 10)

simulation.reporters.append(dcd_reporter)

simulation.runForClockTime(1.0 * openmm.unit.second)
# pymol initial.pdb trajectory.dcd or similar ...

**Comment by mark-cresset** [comment] 2024-03-05 15:58
Thanks for the reply - we'll take a look and see how your suggestions works for us!

**Comment by davidlmobley** [comment] 2024-03-05 20:42
Just a quick comment to @mark-cresset on this:

> Just a ping on this one - we're at a fairly advanced stage of building a force field based on openFF + lots of virtual sites, and the inability to specify an out-of-plane virtual site on an sp2 atom is becoming difficult - we currently have to set up the system with the OpenFF tools and then fiddle with the OpenMM state directly, which is less than optimal. Are there any plans currently to extend the VS code to handle this type of system?

It sounds like this is potentially a request for an extension to the SMIRNOFF spec, particularly our virtual sites: https://docs.openforcefield.org/projects/toolkit/en/0.5.0/smirnoff.html#virtualsites-virtual-sites-for-off-atom-charges

We do not support anything not specified in the spec, and there are no extensions to the spec that would affect this currently under consideration (this is the repo where we do that: https://github.com/openforcefield/standards/blob/main/docs/standards/smirnoff.md ). If you have a specific spec change/extension you would like to propose, we could be willing to consider it. But we're certainly not planning on supporting anything not in the spec. (The process is that FIRST things get put into the spec after our committee works through them to ensure the specification is complete, clear, etc., and then AFTER they are in the spec they get potentially implemented.) 

I haven't dug into all the science on this. But if a spec change is what's being proposed, then ... we'd need to know what the proposed change/extension is.

**Comment by j-wags** [comment] 2024-03-05 23:56
Looking at this with fresh eyes, I think we might be talking about different issues.

I think the issue that Peter and Mark are reporting is that the virtual sites are in plane with the benzene ring, when they should be out of plane. 
<img width="293" alt="Screenshot 2024-03-05 at 3 22 10 PM" src="https://github.com/openforcefield/openff-interchange/assets/16329175/70a29a82-9341-4080-9908-c8987de3b9d2">
<img width="333" alt="Screenshot 2024-03-05 at 3 22 02 PM" src="https://github.com/openforcefield/openff-interchange/assets/16329175/0cd384f2-8116-420f-847c-42d0f0aa78cd">


Matt correctly points out that trivalent vsites are tricky for a variety of reasons, and maybe the root cause of the benzene issue is one of those, but the clear first step is to understand why the trajectories have the vsites in-plane.

I'll chat with Matt tomorrow morning and will update here!

**Comment by j-wags** [comment] 2024-03-06 16:24
I chatted with Matt and we came to the consensus that [we thought we'd fixed the wrong-geometry bug](https://github.com/openforcefield/openff-interchange/issues/922#issuecomment-1980963300) and so we thought you were talking about something else, but instead it looks like the machinery we were using to test our trivalent vsite geometries was testing the wrong thing, so the bug found its way back in. 

So, we're actively working on a fix for this, and in the longer term we're going to discuss whether we need to update/publish a new version of our spec to clarify the behavior of trivalent vsites better. Thanks for your patience on this @peterjohncherry and @mark-cresset - You're the first major users of this functionality and we want to get a fixed turned around for you quickly.

**Comment by j-wags** [comment] 2024-09-18 16:47
I'm going to go ahead and close this issue (though please let me know if I've missed some facet that's unresolved!)

There were two discussions here, and they were resolved as follows:
* Cresset wants a way to model vsites above and below a ring - This was resolved by adding the `OPENFF_UNSAFE_VSITES` flag in https://github.com/openforcefield/openff-toolkit/pull/1887
* TrivalentLonePair vsites don't lie above and below the plane when the 4 atoms are coplanar - This is a valid problem but TrivalentLonePair vsites were always intended to be applied to pyramidal atoms, so it's not clear if this is a bug here or something that should be changed in the SMIRNOFF spec. Thus this is more of a standards question than an Interchange issue.

**Closed by j-wags** 2024-09-18 16:47 UTC
